before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: To/sNfxCLRF/illbKPj8VxB4A+7Kfh9UB70aWcGWTk9GUvXgmUtAvb0GH8A7BL/1gAqvUrIQu56Vbh1/kyDjtsvLo/MTbswRgakBGeeVdeERg4+Ig6OpWwxAmVb6nzkQFc75MSC37CRvzbtYRh7SgvFnz+v5eMing7CZ0vjn6lT3Wvz22FkirGe9voev6I3h/Q5tExgYGDhrk7ikQCwofDH4XiY7td4DM7lfa+PzAHTKIDA3HkyFT6h4svJmE4emAURa2lVB2HJofxfKccdDQdJP4jaGOjJcinYxOHZ/fZM/0zmE9yMC/8zqiRinmrYaHsUTAlyiEmOwfffbmNqkvFFKn6yJsHTcsTNmTDMG+kaMHe88KDItgPjwp2d4CudpYUDqi1sM7IVwutTVI2zSLzjOadGt7MoCY87qkROKDitD5TsVRir+zig2/icJhruKuXw2yDFkyUAxz9/vfMNZ08K3Cge/Dsy3oN2EvpdkUAH34y0LRBxfo33t2sBBZG9Y9pExoHoLOjxzw73vUEOp7pwJnDntQTbL9lIArsaRX1AAqVFdTZpMteWk+mSEw+GT0HeVPb9ueXgcVxazZEBtcfG60IwogqnE2ZwZqEulZwrwJwoGFV3febM3bpxVEsQHGOMRzKSutk8HumuWCGxQkp7a55hawjCdnMjI2H+mw/g= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
